server:
  port: 8084

spring:
  application:
    name: matching-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
