server:
  port: 8085

spring:
  application:
    name: payment-service
  datasource:
    url: ${DB_PAYMENT_URL:jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${DB_PAYMENT_NAME:goride_payment}}
    username: ${POSTGRES_USER:goride_admin}
    password: ${POSTGRES_PASSWORD:goride_dev_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
