server:
  port: 8083

spring:
  application:
    name: trip-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
